# Generated by Django 5.2.1 on 2026-01-20 00:30

from logging import getLogger

import django.db.models.deletion
from django.contrib.auth.models import Group
from django.db import migrations, models

logger = getLogger("borrowd")


def forwards_func(apps, schema_editor):  # type: ignore[no-untyped-def]
    BorrowdGroup = apps.get_model("borrowd_groups", "BorrowdGroup")
    for borrowd_group in BorrowdGroup.objects.all():
        try:
            perms_group = Group.objects.get(
                name=f"{borrowd_group.name}_user_{borrowd_group.created_by.pk}"
            )
            # must use ids here because django complains with an internally inconsistent error
            borrowd_group.perms_group_id = perms_group.id  # type: ignore[attr-defined]
            borrowd_group.save()
        except Group.DoesNotExist:
            logger.warning(
                f"could not find permissions group for borrowd group {borrowd_group.name}, skipping"
            )


def reverse_func(apps, schema_editor):  # type: ignore[no-untyped-def]
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("borrowd_groups", "0004_alter_borrowdgroup_banner_alter_borrowdgroup_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowdgroup",
            name="perms_group",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="auth.group"
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
