# Generated by Django 5.2.1 on 2026-04-02 13:44

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def compute_per_group_unique_name(base_name: str, user_id: int) -> str:
    return f"{base_name}_user_{user_id}"


def fix_creator_perms_group_naming(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    Group = apps.get_model("auth", "Group")
    BorrowdGroup = apps.get_model("borrowd_groups", "BorrowdGroup")
    Membership = apps.get_model("borrowd_groups", "Membership")

    for borrowd_group in BorrowdGroup.objects.select_related(
        "created_by", "perms_group"
    ).iterator():
        creator = borrowd_group.created_by
        expected_name = compute_per_group_unique_name(
            borrowd_group.name,
            creator.pk,
        )

        correct_group, _ = Group.objects.get_or_create(name=expected_name)

        if borrowd_group.perms_group_id != correct_group.pk:
            borrowd_group.perms_group = correct_group
            borrowd_group.save(update_fields=["perms_group"])

        creator_membership = Membership.objects.filter(
            user=creator,
            group=borrowd_group,
        ).first()

        if creator_membership is not None:
            creator_membership.save()


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_groups", "0008_backfill_creator_moderator_memberships"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(
            fix_creator_perms_group_naming,
            migrations.RunPython.noop,
        ),
    ]
