# Generated by Django 5.2.1 on 2026-04-02 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_groups", "0008_backfill_creator_moderator_memberships"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowdgroup",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Set when the record is soft-deleted. NULL means active.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="borrowdgroup",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Who performed the soft-delete. NULL means active or unknown.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
