# Generated by Django 5.2.1 on 2026-04-02 02:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_groups", "0008_alter_borrowdgroup_name_and_more"),
        ("borrowd_groups", "0008_backfill_creator_moderator_memberships"),
    ]

    operations = []
