# Generated by Django 5.2.1 on 2026-04-02 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("borrowd_groups", "0009_fix_creator_perms_group_naming"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowdgroup",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="borrowdgroup",
            constraint=models.UniqueConstraint(
                fields=("name", "created_by"), name="unique_group_by_user"
            ),
        ),
    ]
