# Generated by Django 5.2.1 on 2026-04-14 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_groups", "0009_borrowdgroup_deleted_at_borrowdgroup_deleted_by"),
        ("borrowd_groups", "0010_alter_borrowdgroup_name_and_more"),
    ]

    operations = []
