"""
Django settings for borrowd project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from typing import cast

from django.urls import reverse_lazy

from borrowd.config.env import env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Keep expected stack traces from tests from flooding `manage.py test` output while running tests
IS_RUNNING_MANAGE_PY_TESTS = len(sys.argv) > 1 and sys.argv[1] == "test"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Some platforms (e.g. platform.sh) may generate the secret key per-deploy in a differnt env variable
# this allows us to specify where the secret key will come from, with a fallback for standard local dev conventions
_secret_key_var_name = env("DJANGO_SECRET_KEY_VAR_NAME", default="DJANGO_SECRET_KEY")
SECRET_KEY = env(_secret_key_var_name)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS: list[str] = []

#
# Borrowd settings
#
BORROWD_GROUP_INVITE_EXPIRY_SECONDS: int = 60 * 60 * 24 * 7  # 1 week

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_cotton",
    "borrowd",
    "borrowd_users",  # Must be above `allauth` to use our templates
    "allauth",
    "allauth.account",
    "guardian",  # Must be before borrowd_permissions
    "borrowd_permissions",  # Must be before object-defining apps like borrowd_items and borrowd_groups
    "borrowd_web",
    "borrowd_beta",
    "borrowd_items",
    "borrowd_groups",
    "notifications",  # Must be below apps that send notifications and above borrowd_notifications
    "borrowd_notifications",
    "django_filters",
    "django_vite",
    "django_cleanup.apps.CleanupConfig",  # Must go last https://github.com/un1t/django-cleanup?tab=readme-ov-file#configuration
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "borrowd_beta.middleware.BetaAccessMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "borrowd.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "borrowd_beta.context_processors.beta_status",
            ],
        },
    },
]

# https://django-cotton.com/docs/configuration
COTTON_DIR = "components"

WSGI_APPLICATION = "borrowd.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# AUTH
AUTH_USER_MODEL = "borrowd_users.BorrowdUser"

LOGIN_REDIRECT_URL = reverse_lazy("item-list")

ACCOUNT_ADAPTER = "borrowd_users.adapters.BorrowdAccountAdapter"
ACCOUNT_LOGIN_BY_CODE_FORMAT = {"numeric": True, "dashed": False, "length": 6}
ACCOUNT_LOGIN_BY_CODE_ENABLED = True
ACCOUNT_LOGIN_METHODS = ["email"]

"""
https://docs.allauth.org/en/latest/account/forms.html
This overrides the change_password form shown in allauth.
change_password: Uses SetPasswordForm instead of ChangePasswordForm to skip
the need to provide the user's current password.
This means users don't need to enter their current password when changing it.
This is a UX decision.
Security note: this means anyone with access
to a logged-in session can change the password.
"""
ACCOUNT_FORMS = {
    "change_password": "borrowd_users.forms.ChangePasswordForm",
}

# Render template rather than simply returning 403 status code with
# no content
GUARDIAN_RENDER_403 = True
# Don't create the user named AnonymousUser. We don't need to give
# object-level permisions to logged-out users, so reduce complexity.
ANONYMOUS_USER_NAME = None

# django-allauth configurations
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
    "guardian.backends.ObjectPermissionBackend",
]

# Email

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# URL to build links when HttpRequest not available (e.g. email notifications)
BASE_URL = "http://localhost:8000"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
BUILD_DIR = BASE_DIR / "build"
if BUILD_DIR.exists():
    STATICFILES_DIRS.append(BUILD_DIR)

STATIC_URL = "static/"

# Media files settings
# https://docs.djangoproject.com/en/5.2/ref/settings/#media-root
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# borrowd_beta settings
BORROWD_BETA_ENABLED = env.bool("BORROWD_BETA_ENABLED", default=False)
BETA_SIGNUP_REDIRECT_PATH = "/"
BETA_CHECK_EXCLUDE_PATHS = [
    r"^/favicon.ico$",
    r"^/admin/.*",
    r"^/static/.*",
    r"^/media/.*",
    r"^/beta/.*",
    r"^/__reload__/.*",
]
BETA_COOKIE_DOMAIN: str | None = None
BETA_SECURE_COOKIE: bool = False
BETA_COOKIE_SAMESITE = "Lax"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": env("DJANGO_LOG_LEVEL", default="INFO").upper(),
            "propagate": False,
        },
        "borrowd": {
            "handlers": ["console"],
            "level": env("DJANGO_LOG_LEVEL", default="INFO").upper(),
            "propagate": False,
        },
    },
}

# Keep expected stack traces from tests from flooding `manage.py test` output while running tests
if IS_RUNNING_MANAGE_PY_TESTS:
    logging_configuration_loggers = cast(
        dict[str, dict[str, object]],
        LOGGING["loggers"],
    )
    logging_configuration_loggers["django.request"] = {
        "handlers": ["console"],
        "level": "CRITICAL",
        "propagate": False,
    }

SENTRY_DSN = "https://ba24455003326bec7fc90b49af2d5c27@o4510502108594176.ingest.us.sentry.io/4510660596137984"

#
# Shim for mypy to play nice with certain generic types
#
from django.db.models import (  # noqa: E402
    BooleanField,
    CharField,
    DateTimeField,
    ForeignKey,
    IntegerField,
    ManyToManyField,
    TextField,
)
from django.db.models.manager import BaseManager  # noqa: E402
from django.db.models.query import QuerySet  # noqa: E402
from django.forms import ModelForm  # noqa: E402
from django.views.generic import (  # noqa: E402
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

# NOTE: there are probably other items you'll need to monkey patch depending on
# your version.
for cls in [
    BaseManager,
    BooleanField,
    CharField,
    CreateView,
    DateTimeField,
    DeleteView,
    DetailView,
    ForeignKey,
    IntegerField,
    ListView,
    ManyToManyField,
    ModelForm,
    QuerySet,
    TextField,
    UpdateView,
]:
    cls.__class_getitem__ = classmethod(lambda cls, *args, **kwargs: cls)  # type: ignore [attr-defined]
