blank_issues_enabled: false
contact_links:
  - name: Read Before Opening an Issue
    url: https://github.com/borrowd/borrowd/blob/main/docs/CONTRIBUTING.md
    about: Please read our Contributing Guide for guidelines on reporting issues and contributing to borrowd.
