# Generated by Django 5.2.1 on 2026-03-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0014_availabilitysubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.IntegerField(
                choices=[
                    (10, "Available"),
                    (15, "Requested"),
                    (20, "Reserved"),
                    (30, "Borrowed"),
                ],
                default=10,
                help_text="The current status of the Item.",
            ),
        ),
    ]
