# Generated by Django 5.2.1 on 2026-04-02 22:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

from borrowd_users.system import SYSTEM_USER_USERNAME


def backfill_audit_fields(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    BorrowdUser = apps.get_model("borrowd_users", "BorrowdUser")
    system_user = BorrowdUser.objects.get(username=SYSTEM_USER_USERNAME)

    Item = apps.get_model("borrowd_items", "Item")
    Item.objects.filter(created_by_id=None).update(created_by_id=system_user.pk)
    Item.objects.filter(updated_by_id=None).update(updated_by_id=system_user.pk)

    ItemPhoto = apps.get_model("borrowd_items", "ItemPhoto")
    ItemPhoto.objects.filter(created_by_id=None).update(created_by_id=system_user.pk)
    ItemPhoto.objects.filter(updated_by_id=None).update(updated_by_id=system_user.pk)

    Transaction = apps.get_model("borrowd_items", "Transaction")
    Transaction.objects.filter(created_by_id=None).update(created_by_id=system_user.pk)


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0015_alter_item_status"),
        ("borrowd_users", "0010_create_system_user"),
    ]

    operations = [
        # all _by fields are nullable, no need to default
        migrations.AddField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="The date and time at which the item was created.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Set when the record is soft-deleted. NULL means active.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Who performed the soft-delete. NULL means active or unknown.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time at which the item was last updated.",
            ),
        ),
        migrations.AddField(
            model_name="itemphoto",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="The date and time at which the item photo was created.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itemphoto",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Set when the record is soft-deleted. NULL means active.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="itemphoto",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Who performed the soft-delete. NULL means active or unknown.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="itemphoto",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time at which the item photo was last updated.",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Set when the record is soft-deleted. NULL means active.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Who performed the soft-delete. NULL means active or unknown.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time at which the transaction was created.",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time at which the transaction was last updated.",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="updated_by",
            field=models.ForeignKey(
                help_text="The last user who updated the transaction.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # _by are non-nullable. We need to do: nullable > backfill > non-nullable
        # step: nullable
        migrations.AddField(
            model_name="item",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                default=None,
                help_text="The user who created the item.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                default=None,
                help_text="The last user who updated the item.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itemphoto",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                default=None,
                help_text="The user who created the item photo.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itemphoto",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                default=None,
                help_text="The last user who updated the item photo.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                default=None,
                help_text="The user who created the transaction.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        # step: backfill
        migrations.RunPython(backfill_audit_fields, migrations.RunPython.noop),
        # step: non-nullable
        migrations.AlterField(
            model_name="item",
            name="created_by",
            field=models.ForeignKey(
                null=False,
                help_text="The user who created the item.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="updated_by",
            field=models.ForeignKey(
                null=False,
                help_text="The last user who updated the item.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="itemphoto",
            name="created_by",
            field=models.ForeignKey(
                null=False,
                help_text="The user who created the item photo.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="itemphoto",
            name="updated_by",
            field=models.ForeignKey(
                null=False,
                help_text="The last user who updated the item photo.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_by",
            field=models.ForeignKey(
                null=False,
                help_text="The user who created the transaction.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
