# Generated by Django 5.2.1 on 2026-04-02 22:31

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

from borrowd_users.system import SYSTEM_USER_USERNAME


def backfill_audit_fields(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    BorrowdUser = apps.get_model("borrowd_users", "BorrowdUser")
    system_user = BorrowdUser.objects.get(username=SYSTEM_USER_USERNAME)

    Item = apps.get_model("borrowd_items", "Item")
    Item.objects.filter(created_by_id=None).update(created_by_id=system_user.pk)
    Item.objects.filter(updated_by_id=None).update(updated_by_id=system_user.pk)

    ItemPhoto = apps.get_model("borrowd_items", "ItemPhoto")
    ItemPhoto.objects.filter(created_by_id=None).update(created_by_id=system_user.pk)
    ItemPhoto.objects.filter(updated_by_id=None).update(updated_by_id=system_user.pk)

    Transaction = apps.get_model("borrowd_items", "Transaction")
    Transaction.objects.filter(created_by_id=None).update(created_by_id=system_user.pk)


class Migration(migrations.Migration):
    dependencies = [("borrowd_items", "0016_audit_1")]

    operations = [
        # step: backfill
        migrations.RunPython(backfill_audit_fields, migrations.RunPython.noop),
    ]
