# Generated by Django 5.2.1 on 2026-04-02 22:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0017_audit_2"),
    ]

    operations = [
        # step: non-nullable
        migrations.AlterField(
            model_name="item",
            name="created_by",
            field=models.ForeignKey(
                null=False,
                help_text="The user who created the item.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="updated_by",
            field=models.ForeignKey(
                null=False,
                help_text="The last user who updated the item.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="itemphoto",
            name="created_by",
            field=models.ForeignKey(
                null=False,
                help_text="The user who created the item photo.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="itemphoto",
            name="updated_by",
            field=models.ForeignKey(
                null=False,
                help_text="The last user who updated the item photo.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_by",
            field=models.ForeignKey(
                null=False,
                help_text="The user who created the transaction.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
