# Generated by Django 5.2.1 on 2026-03-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowd_users', '0007_searchterm'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='searchterm',
            index=models.Index(fields=['user', 'target', '-created_at'], name='borrowd_use_user_id_c69e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='searchterm',
            index=models.Index(fields=['target', '-created_at'], name='borrowd_use_target_7d8e20_idx'),
        ),
    ]
