# Generated by Django 5.2.1 on 2026-04-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_users", "0008_searchterm_borrowd_use_user_id_c69e4a_idx_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="searchterm",
            new_name="borrowd_use_user_id_7b1018_idx",
            old_name="borrowd_use_user_id_c69e4a_idx",
        ),
        migrations.RenameIndex(
            model_name="searchterm",
            new_name="borrowd_use_target_e24bf8_idx",
            old_name="borrowd_use_target_7d8e20_idx",
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
