# Generated by Django 5.2.1 on 2026-04-02 16:38

from django.contrib.auth.hashers import make_password
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

from borrowd_users.system import SYSTEM_USER_USERNAME


def create_system_user(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor):
    BorrowdUser = apps.get_model("borrowd_users", "BorrowdUser")
    BorrowdUser.objects.get_or_create(
        username=SYSTEM_USER_USERNAME,
        defaults={
            "password": make_password(None),
            "first_name": "System",
            "last_name": "User",
            "is_active": False,
            "is_staff": False,
            "is_superuser": False,
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_users", "0009_increase_bio_max_length"),
    ]

    operations = [migrations.RunPython(create_system_user, migrations.RunPython.noop)]
