# Generated by Django 5.2.1 on 2026-04-02 19:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps
from django.db.models import F


def backfill_profile_audit_fields(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    Profile = apps.get_model("borrowd_users", "Profile")
    Profile.objects.update(created_by_id=F("user_id"), updated_by_id=F("user_id"))


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_users", "0010_create_system_user"),
    ]

    operations = [
        # all _by fields are nullable, no need to default
        migrations.AddField(
            model_name="borrowduser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="The date and time at which the user was created.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="borrowduser",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user who created the user.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="borrowduser",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Set when the record is soft-deleted. NULL means active.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="borrowduser",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Who performed the soft-delete. NULL means active or unknown.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="borrowduser",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time at which the user was last updated.",
            ),
        ),
        migrations.AddField(
            model_name="borrowduser",
            name="updated_by",
            field=models.ForeignKey(
                help_text="The last user who updated the user.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="The date and time at which the profile was created.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Set when the record is soft-deleted. NULL means active.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Who performed the soft-delete. NULL means active or unknown.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time at which the profile was last updated.",
            ),
        ),
        # _by are non-nullable. We need to do: nullable > backfill > non-nullable
        # step: nullable
        migrations.AddField(
            model_name="profile",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                default=None,
                help_text="The user who created the profile.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                default=None,
                help_text="The last user who updated the profile.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        # step: backfill
        migrations.RunPython(backfill_profile_audit_fields, migrations.RunPython.noop),
        # step: non-nullable
        migrations.AlterField(
            model_name="profile",
            name="created_by",
            field=models.ForeignKey(
                null=False,
                help_text="The user who created the profile.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="updated_by",
            field=models.ForeignKey(
                null=False,
                help_text="The last user who updated the profile.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
